### ISSUE TITLE
Read .babelrc.json?

### ISSUE THREAD

**Issue by ashleysommer** [lemmon/babel-env-cli#1]
Hi @lemmon Thank you for creating and maintaining this handy tool.

I'm using it in a project of mine, and I'm just wondering if its possible to make it read in additional babel config settings via a `.babelrc.json` file?

I need to set "sourceMaps: true" and I thought it would be as simple as putting a `.babelrc.json` file with that option in my working directory, but when using this tool `babel` doesn't seem to load or read that file.

I'd also ideally like to pass `preset-env` options too, specifically 'modules: "amd"', but I realize that might be harder because the `presets` list is hardcoded in the tool.

Thanks for any help you can offer.

**Comment by lemmon** [comment]
Hi, first of all, thank you for taking interest in this little side-project of mine. To answer your questions:

a) That's a very good point. I was under impression that it might work automatically since babel reads browserlist settings from your project folder. I am not using any additional options so I have not tested this at all. I'll check and come back to you.

b) My understanding is that this is not possible. It would mean combiding global and local modules. The sole reason for creating this tool was the very problem -- I wanted to use babel-cli with babel-env as a global package. So I am affraid that if you want use any additional modules you need to fork this repo and hardcode them.

**Comment by ashleysommer** [comment]
Hi @lemmon 
Thanks for your response.
Would be awesome if we could get this working, my main feature requirement is to have sourcemaps optionally generated by babel. If its not possible via `.babelrc.json` then perhaps it might be possible via a commandline switch to `babel-env-cli`?

**Comment by lemmon** [comment]
@ashleysommer I was not completelly mistaken that babel automatically reads either package.json or baberc files. However, only inline source maps worked.

I've included external source maps in v0.4.0, please checks if it works.

**Comment by ashleysommer** [comment]
Hi @lemmon 
I was going to reply saying its still not working for me, but then I realized my subprocess runner in my application was using `babel-env-cli` by passing the sourcefile contents to stdin, and reading the response from stdout. Thats also the reason I was not able to get 'inline' sourcemaps working previously too.

Changed it to pass the filename and write to an output file, and now I'm getting the sourcemaps I need. Thank you!
